[versions]
agp = "8.6.1"
androidMavenGradlePlugin = "2.1"
geotracking = "1"
alerter = "7.2.4"
glide = "4.16.0"
koinCore = "3.4.3"
koinTest = "3.4.3"
koinTestJunit4 = "3.4.3"
kotlin = "1.9.0"
coreKtx = "1.13.1"


junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
krealmextensions = "2.5.0"
lifecycleRuntimeKtx = "2.8.6"
activityCompose = "1.9.2"
composeBom = "2024.09.02"
appcompat = "1.7.0"
material = "1.12.0"
multidex = "2.0.1"
branch ="5.0.3"
picasso = "2.71828"
playServicesLocation = "21.3.0"
playServicesMaps = "19.0.0"
realm = "10.19.0"
recyclerview = "1.3.2"
sdpAndroid = "1.1.1"
sspAndroid = "1.1.1"


[libraries]
android-maven-gradle-plugin = { module = "com.github.dcendents:android-maven-gradle-plugin", version.ref = "androidMavenGradlePlugin" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }

koin-android = { module = "io.insert-koin:koin-android" , version.ref = "koinCore" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koinCore" }
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koinTest" }
koin-test-junit4 = { module = "io.insert-koin:koin-test-junit4", version.ref = "koinTestJunit4" }
kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom" }
krealmextensions = { module = "com.github.vicpinm:krealmextensions", version.ref = "krealmextensions" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

multidex = { group = "androidx.multidex", name = "multidex" , version.ref = "multidex"}
branch = { group = "io.branch.sdk.android", name = "library", version.ref = "branch" }
picasso = { module = "com.squareup.picasso:picasso", version.ref = "picasso" }
play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "playServicesLocation" }
play-services-maps = { module = "com.google.android.gms:play-services-maps", version.ref = "playServicesMaps" }
sdp-android = { module = "com.intuit.sdp:sdp-android", version.ref = "sdpAndroid" }


realm = { module = "io.realm:realm-gradle-plugin", version.ref = "realm" }
ssp-android = { module = "com.intuit.ssp:ssp-android", version.ref = "sspAndroid" }






[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }




